// Generated by CoffeeScript 1.7.1
(function() {
  var cache, candiateWords, fs, getFilePath, path, removePunctuation, stopwords, _;

  path = require('path');

  fs = require('fs');

  _ = require('lodash');

  cache = {};

  getFilePath = function(language) {
    return path.join(__dirname, "..", "data", "stopwords", "stopwords-" + language + ".txt");
  };

  module.exports = stopwords = function(content, language) {
    var count, filePath, overlappingStopwords, stopWords, strippedInput, words;
    if (language == null) {
      language = 'en';
    }
    filePath = getFilePath(language);
    if (!fs.existsSync(filePath)) {
      filePath = getFilePath('en');
    }
    if (cache.hasOwnProperty(language)) {
      stopWords = cache[language];
    } else {
      stopWords = fs.readFileSync(filePath).toString().split('\n');
      cache[language] = stopWords;
    }
    strippedInput = removePunctuation(content);
    words = candiateWords(strippedInput);
    overlappingStopwords = [];
    count = 0;
    _.each(words, function(w) {
      count += 1;
      if (stopWords.indexOf(w.toLowerCase()) > -1) {
        return overlappingStopwords.push(w.toLowerCase());
      }
    });
    return {
      wordCount: count,
      stopwordCount: overlappingStopwords.length,
      stopWords: overlappingStopwords
    };
  };

  removePunctuation = function(content) {
    return content.replace(/[\|\@\<\>\[\]\"\'\.,-\/#\?!$%\^&\*\+;:{}=\-_`~()]/g, "");
  };

  candiateWords = function(strippedInput) {
    return strippedInput.split(' ');
  };

}).call(this);
